version: '3.7'
services:
  cart-service:
    build: .
    ports:
      - "8080:8080"
    networks:
      - juices

  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=root
    ports:
      - "5431:5431"
      - "5432:5432"
    networks:
      - juices

networks:
  juices:
    driver: bridge

